from PyQt5 import QtCore, QtWidgets, QtGui


class Ui_Messager(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(700, 600)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.chatArea = QtWidgets.QTextEdit(self.centralwidget)
        self.chatArea.setGeometry(QtCore.QRect(280, 10, 400, 450))
        self.chatArea.setObjectName("chatArea")
        self.chatArea.setReadOnly(True)
        self.messageArea = QtWidgets.QTextEdit(self.centralwidget)
        self.messageArea.setGeometry(QtCore.QRect(280, 470, 320, 75))
        self.messageArea.setObjectName("messageArea")
        self.pushButton = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton.setGeometry(QtCore.QRect(605, 470, 75, 75))
        self.pushButton.setObjectName("pushButton")
        self.contacts = QtWidgets.QListWidget(self.centralwidget)
        self.contacts.setGeometry(QtCore.QRect(10, 10, 261, 535))
        self.contacts.setObjectName("contacts")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 700, 21))
        self.menubar.setObjectName("menubar")
        self.menuFile = QtWidgets.QMenu(self.menubar)
        self.menuFile.setObjectName("menuFile")
        self.menu = QtWidgets.QMenu(self.menubar)
        self.menu.setObjectName("menu")
        self.menu_2 = QtWidgets.QMenu(self.menubar)
        self.menu_2.setObjectName("menu_2")
        self.menu_3 = QtWidgets.QMenu(self.menubar)
        self.menu_3.setObjectName("menu_3")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.add_contact = QtWidgets.QAction(MainWindow)
        self.add_contact.setObjectName("add_contact")
        self.contact_name = QtWidgets.QInputDialog(MainWindow)
        self.contact_name.setObjectName('contact_name')
        self.contact_name.setGeometry(QtCore.QRect(350, 350, 100, 100))
        self.action_2 = QtWidgets.QAction(MainWindow)
        self.action_2.setObjectName("action_2")
        self.authorization = QtWidgets.QAction(MainWindow)
        self.authorization.setObjectName("authorization")
        self.authorization_form = QtWidgets.QInputDialog(MainWindow)
        self.authorization_form.setObjectName('authorization_form')
        self.registration = QtWidgets.QAction(MainWindow)
        self.registration.setObjectName("registration")
        self.registration_form = QtWidgets.QInputDialog(MainWindow)
        self.registration_form.setObjectName('registration_form')
        self.menuFile.addAction(self.add_contact)
        self.menu.addAction(self.action_2)
        self.menu.addSeparator()
        self.menu.addAction(self.authorization)
        self.menu.addAction(self.registration)
        self.menubar.addAction(self.menuFile.menuAction())
        self.menubar.addAction(self.menu.menuAction())
        self.menubar.addAction(self.menu_2.menuAction())
        self.menubar.addAction(self.menu_3.menuAction())

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Messenger"))
        self.pushButton.setText(_translate("MainWindow", "Отправить"))
        self.menuFile.setTitle(_translate("MainWindow", "Контакты"))
        self.menu.setTitle(_translate("MainWindow", "Аккаунт"))
        self.menu_2.setTitle(_translate("MainWindow", "Настройки"))
        self.menu_3.setTitle(_translate("MainWindow", "Помощь"))
        self.add_contact.setText(_translate("MainWindow", "Добавить контакт"))
        self.action_2.setText(_translate("MainWindow", "Настройки аккаунта"))
        self.authorization.setText(_translate("MainWindow", "Вход"))
        self.registration.setText(_translate("MainWindow", "Регистрация"))
